# Schedule {-}

### Week 1 {-}

- Thursday, January 23    
    Introductions, review of key ideas from STAT 155, why we need causal stories (graphs!)    
    Slides from class are available [here](https://docs.google.com/presentation/d/1SNGxtjUwv4T-hDY7fgamMCF0I5-WpzOv6G1jRzw3QhA/edit?usp=sharing).
    - **After class:**    
        Recommended reading: PRIMER, Chapter 1: Sections 1.1, 1.2    
        Required reading: PRIMER, Chapter 1: 1.4, 1.5.1

### Week 2 {-}

- Thursday, January 30    
    The mathematics (probability) of graphs
    - **Before class:**    
        Please watch the following two videos and/or read the corresponding sections of PRIMER. Answer the Moodle questions before class.    
        Video 1: [Essentials of Probability](https://youtu.be/acofPsJDq5Y), ([slides](https://drive.google.com/file/d/1D8abGhrW99kbrlrMeLi3yogfpXwMmBc7/view?usp=sharing))    
        Video 2: [Key Structure in DAGs](https://youtu.be/Mh4G4QgrzYs), ([slides](https://drive.google.com/file/d/1F2hHqMOzyABQ7RH7owUdutWGrsdCR1qu/view?usp=sharing))    
        Reading: PRIMER, Chapter 1: Sections 1.3.1 to 1.3.5, Chapter 2: Sections 2.1 to 2.3

### Week 3 {-}

- Tuesday, February 4    
    d-separation and its applications for understanding bias
    - **Before class:**    
        Reading: PRIMER, Chapter 2: Section 2.4. There is one associated Moodle question for this reading.    
        Please also read the article *The Birth Weight "Paradox" Uncovered?* available in the Readings section on Moodle. We will discuss in class on Tuesday.
- Tuesday, February 4    
    d-separation and its applications for understanding bias (continued)    
    No new reading. Work on [Homework 1], due Thursday, February 13 in class.


### Week 4 {-}

- Tuesday, February 11    
    The do-operator and estimating causal effects    
    - **Before class:**    
        Required reading: PRIMER, Chapter 1: 1.3.6 and 1.3.7, Chapter 3: Sections 3.1 through 3.3 (skip 3.2.2 on Multiple Interventions). Answer the Moodle questions (under "The do-operator and estimating causal effects") before class.
- Thursday, February 13    
    The do-operator and estimating causal effects (continued)


### Week 5 {-}

- Tuesday, February 18    
    The do-operator and estimating causal effects (continued)
- Thursday, February 20    
    Inverse probability weighting and structural models    
    - **Before class:**    
        Required reading: WHATIF Sections 1.1 to 1.3 (Chapter 1: A definition of causal effect) and Chapter 12: IP weighting and marginal structural models.    
        No Moodle questions this week. Just read to familiarize yourselves with the ideas, which we'll discuss in class this week. Chapter 12 is a little more technical - let the following questions guide your reading:    
        - What is the concept of the "pseudo-population"? What is the nice characteristic that it has? How does IP weighting achieve that characteristic?
        - How are stabilized IP weights different from ordinary (unstabilized) weights? Why would we want to use stabilized weights?
        - What is a marginal structural model, and how are they fit? What parameters of these models are of interest?
        - How is IP weighting used in dealing with censoring (loss-to-follow up / selection bias)?

### Week 6 {-}

- Tuesday, February 25    
    IP weighting to account for selection bias
- Thursday, February 27    
    No class - Capstone Days!


### Week 7 {-}

- Tuesday, March 3    
    Causal discovery
- Thursday, March 5    
    Causal discovery


### Week 8 {-}

- Tuesday, March 3    
    Sensitivity analyses for unmeasured confounding
- Thursday, March 5    
    Project work day

### Spring Break: 3/16 - 3/27 {-}

### Week 9: 3/30 - 4/3 {-}

<span style="color:red">
If Google/YouTube access is a problem, all videos and slides are also available on Moodle in the "Videos & Slides" section. All Moodle questions are in the "Reading/Video Questions" section.
</span>

- Tuesday, March 31    
    Mediation analysis ([video](https://youtu.be/hP409M9zYyA), [slides](https://drive.google.com/file/d/17TenllqG_RMJ-vDFsRcmCXw6HWZyAjl4/view?usp=sharing))    
    Moodle questions: [Mediation Analysis](https://moodle.macalester.edu/mod/quiz/view.php?id=36874) due Wednesday, April 1 at midnight (CST)
- Thursday, April 2    
    Mediation analysis (continued)




